name = "cloudflare-docker-proxy"
main = "src/index.js"
compatibility_date = "2023-12-01"

[dev]
ip = "0.0.0.0"
port = 8787
local_protocol = "http"

[vars]
CUSTOM_DOMAIN = "tangtao.name"

[env.dev.vars]
MODE = "debug"
TARGET_UPSTREAM = "https://registry-1.docker.io"
CUSTOM_DOMAIN = "tangtao.name"

[env.production]
name = "cloudflare-docker-proxy"
routes = [
  { pattern = "docker.tangtao.name", custom_domain = true },
  { pattern = "quay.tangtao.name", custom_domain = true },
  { pattern = "gcr.tangtao.name", custom_domain = true },
  { pattern = "k8s-gcr.tangtao.name", custom_domain = true },
  { pattern = "k8s.tangtao.name", custom_domain = true },
  { pattern = "ghcr.tangtao.name", custom_domain = true },
  { pattern = "cloudsmith.tangtao.name", custom_domain = true },
]

[env.production.vars]
MODE = "production"
TARGET_UPSTREAM = ""

[env.staging]
name = "cloudflare-docker-proxy-staging"
# route = { pattern = "docker-staging.libcuda.so", custom_domain = true }

[env.staging.vars]
MODE = "staging"
TARGET_UPSTREAM = ""
